IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'URLS')
BEGIN
	CREATE TABLE URLS ( 
		ID_column INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		url VARCHAR(MAX) not null
	);
END
